name: Python application

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        HEROKU_API_KEY: ${{ secrets.WHAT_YOU_CALL_THIS_DOESNT_MATTER_BUT_PLEASE_REMEMBER_THE_NAME }}
    steps:
    - uses: actions/checkout@v2
    - name: Login to Heroku Container registry
      run: heroku container:login
    - name: Build and push
      run: heroku container:push -a docker-deploy-thing web
    - name: Release
      run: heroku container:release -a docker-deploy-thing web
      
